-- Baseline schema — the exact tables the Spring Boot backend (Hibernate
-- ddl-auto=update) used to create and maintain on its own.
--
-- Everything here is idempotent:
--   * On a brand-new database it creates the whole schema.
--   * On a database that the old Java backend already populated it is a
--     no-op, apart from the handful of drift fixes at the bottom (legacy
--     NOT NULL constraints that Hibernate never relaxed).
--
-- Column names/types intentionally mirror Hibernate's naming
-- (camelCase -> snake_case) so an existing database can be pointed at the
-- new backend with `pg_dump | psql` and nothing else.

CREATE TABLE IF NOT EXISTS app_user (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bio                    text,
    bookable               boolean NOT NULL DEFAULT true,
    created_at             timestamp(6) without time zone,
    job_title              varchar(255),
    name                   varchar(255),
    password               varchar(255) NOT NULL,
    profile_image_url      text,
    role                   varchar(255) NOT NULL,
    slug                   varchar(255) UNIQUE,
    updated_at             timestamp(6) without time zone,
    username               varchar(255) NOT NULL UNIQUE,
    account_type           varchar(255) CHECK (account_type IN ('INDIVIDUAL', 'CLINIC')),
    permissions            text,
    tenant_id              bigint,
    enabled                boolean NOT NULL DEFAULT true,
    phone                  varchar(255),
    credentials_changed_at timestamp(6) without time zone
);

CREATE TABLE IF NOT EXISTS patient (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    additional_notes        text,
    created_at              timestamp(6) without time zone,
    email                   varchar(255),
    name                    varchar(255) NOT NULL,
    phone                   varchar(255) NOT NULL,
    primary_psychologist_id bigint NOT NULL,
    risk_flag               boolean NOT NULL DEFAULT false,
    risk_flagged_at         timestamp(6) without time zone,
    risk_reason             text,
    source                  varchar(255) NOT NULL DEFAULT 'Direct',
    telegram_chat_id        varchar(255),
    updated_at              timestamp(6) without time zone,
    assigned_doctor_id      bigint,
    CONSTRAINT patient_phone_owner_uk UNIQUE (phone, primary_psychologist_id)
);

CREATE TABLE IF NOT EXISTS appointment (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date          date NOT NULL,
    cancellation_reason       varchar(255),
    created_at                timestamp(6) without time zone,
    end_time                  time(6) without time zone NOT NULL,
    feedback                  text,
    google_calendar_event_id  varchar(255),
    notes                     text,
    payment_screenshot_base64 text,
    previous_appointment_id   bigint,
    psychologist_id           bigint NOT NULL,
    rating                    integer,
    session_type              varchar(255),
    start_time                time(6) without time zone NOT NULL,
    status                    varchar(255) NOT NULL,
    tracking_token            varchar(25) NOT NULL UNIQUE,
    updated_at                timestamp(6) without time zone,
    patient_id                bigint NOT NULL REFERENCES patient (id),
    assigned_doctor_id        bigint,
    mode                      varchar(255)
);

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action                 varchar(255) NOT NULL,
    admin_user_id          bigint NOT NULL,
    created_at             timestamp(6) without time zone,
    detail                 text,
    target_psychologist_id bigint
);

CREATE TABLE IF NOT EXISTS bank_account (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name    varchar(255),
    account_number  varchar(255),
    active          boolean NOT NULL DEFAULT true,
    bank_name       varchar(255),
    ifsc_code       varchar(255),
    is_default      boolean NOT NULL DEFAULT false,
    psychologist_id bigint NOT NULL,
    qr_code_base64  text,
    upi_id          varchar(255)
);

CREATE TABLE IF NOT EXISTS clinic_holiday (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date    date NOT NULL,
    psychologist_id bigint NOT NULL,
    reason          varchar(255),
    CONSTRAINT clinic_holiday_date_owner_uk UNIQUE (holiday_date, psychologist_id)
);

CREATE TABLE IF NOT EXISTS clinic_service (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active          boolean NOT NULL DEFAULT true,
    created_at      timestamp(6) without time zone,
    description     text,
    display_order   integer NOT NULL DEFAULT 0,
    duration        varchar(255) NOT NULL,
    fee             numeric(10, 2),
    icon            varchar(255),
    name            varchar(255) NOT NULL,
    psychologist_id bigint NOT NULL,
    updated_at      timestamp(6) without time zone
);

CREATE TABLE IF NOT EXISTS clinic_settings (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address            varchar(255),
    bank_account_name  varchar(255),
    clinic_name        varchar(255),
    contact_email      varchar(255),
    contact_phone      varchar(255),
    demo_call_number   varchar(255),
    doctor_name        varchar(255),
    payment_qr_code_url text,
    psychologist_id    bigint NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS doctor_availability_block (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week      varchar(255) NOT NULL,
    end_time         varchar(255) NOT NULL,
    interval_minutes integer NOT NULL,
    start_time       varchar(255) NOT NULL,
    psychologist_id  bigint NOT NULL REFERENCES app_user (id),
    mode             varchar(255)
);

CREATE TABLE IF NOT EXISTS doctor_date_override (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available       boolean NOT NULL,
    slot_time       varchar(255),
    specific_date   date NOT NULL,
    psychologist_id bigint NOT NULL REFERENCES app_user (id),
    mode            varchar(255)
);

CREATE TABLE IF NOT EXISTS doctor_weekly_slot (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active          boolean NOT NULL,
    day_of_week     varchar(255) NOT NULL,
    slot_time       varchar(255) NOT NULL,
    psychologist_id bigint NOT NULL REFERENCES app_user (id),
    mode            varchar(255)
);

CREATE TABLE IF NOT EXISTS doctor_service_price (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_service_id bigint NOT NULL REFERENCES clinic_service (id),
    psychologist_id   bigint NOT NULL REFERENCES app_user (id),
    offline_offered   boolean NOT NULL DEFAULT false,
    offline_price     numeric(38, 2),
    online_offered    boolean NOT NULL DEFAULT false,
    online_price      numeric(38, 2),
    CONSTRAINT doctor_service_price_doc_svc_uk UNIQUE (psychologist_id, clinic_service_id)
);

CREATE TABLE IF NOT EXISTS invoice (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount             numeric(10, 2) NOT NULL,
    bank_account_id    bigint,
    bank_account_name  varchar(255),
    created_at         timestamp(6) without time zone,
    discount_amount    numeric(10, 2),
    discount_reason    varchar(255),
    paid_at            date,
    payment_method     varchar(255),
    psychologist_id    bigint NOT NULL,
    remark             varchar(255),
    status             varchar(255) NOT NULL,
    updated_at         timestamp(6) without time zone,
    appointment_id     bigint NOT NULL UNIQUE REFERENCES appointment (id),
    patient_id         bigint NOT NULL REFERENCES patient (id),
    payment_handled_by varchar(20) NOT NULL DEFAULT 'SELF',
    version            bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoice_payment (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount               numeric(10, 2) NOT NULL,
    bank_account_id      bigint,
    bank_account_name    varchar(255),
    collected_by_staff_id bigint,
    created_at           timestamp(6) without time zone,
    paid_at              timestamp(6) without time zone NOT NULL,
    payment_method       varchar(255),
    remark               varchar(255),
    invoice_id           bigint NOT NULL REFERENCES invoice (id)
);

CREATE TABLE IF NOT EXISTS lead (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id  bigint,
    converted_at    timestamp(6) without time zone,
    created_at      timestamp(6) without time zone,
    email           varchar(255),
    name            varchar(255) NOT NULL,
    notes           text,
    patient_id      bigint,
    phone           varchar(255) NOT NULL,
    practitioner_id bigint NOT NULL,
    status          varchar(255) NOT NULL,
    updated_at      timestamp(6) without time zone
);

CREATE TABLE IF NOT EXISTS mood_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6) without time zone,
    log_date        date NOT NULL,
    mood_score      integer NOT NULL,
    note            text,
    psychologist_id bigint NOT NULL,
    appointment_id  bigint REFERENCES appointment (id),
    patient_id      bigint NOT NULL REFERENCES patient (id)
);

CREATE TABLE IF NOT EXISTS notification_log (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_message  text,
    sent_at        timestamp(6) without time zone,
    status         varchar(255) NOT NULL,
    type           varchar(255) NOT NULL,
    appointment_id bigint REFERENCES appointment (id)
);

CREATE TABLE IF NOT EXISTS patient_attachment (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_data       text NOT NULL,
    file_name       varchar(255) NOT NULL,
    file_size       bigint NOT NULL,
    file_type       varchar(100) NOT NULL,
    psychologist_id bigint NOT NULL,
    uploaded_at     timestamp(6) without time zone,
    patient_id      bigint NOT NULL REFERENCES patient (id)
);

CREATE TABLE IF NOT EXISTS payment_submission (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount_claimed       numeric(38, 2),
    created_at           timestamp(6) without time zone,
    psychologist_id      bigint NOT NULL,
    review_note          text,
    reviewed_at          timestamp(6) without time zone,
    reviewed_by_admin_id bigint,
    screenshot_base64    text,
    status               varchar(255) NOT NULL,
    upi_transaction_ref  varchar(100) NOT NULL,
    version              bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rebook_request (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rebooked_at             timestamp(6) without time zone,
    new_appointment_id      bigint NOT NULL UNIQUE REFERENCES appointment (id),
    original_appointment_id bigint NOT NULL UNIQUE REFERENCES appointment (id)
);

CREATE TABLE IF NOT EXISTS session_note (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment      text,
    content         text,
    created_at      timestamp(6) without time zone,
    objective       text,
    plan            text,
    psychologist_id bigint NOT NULL,
    subjective      text,
    updated_at      timestamp(6) without time zone,
    appointment_id  bigint NOT NULL UNIQUE REFERENCES appointment (id),
    patient_id      bigint NOT NULL REFERENCES patient (id)
);

CREATE TABLE IF NOT EXISTS staff_attendance (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         date NOT NULL,
    login_time   timestamp(6) without time zone NOT NULL,
    logout_time  timestamp(6) without time zone,
    work_minutes bigint,
    staff_id     bigint NOT NULL REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS subscription (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount               numeric(38, 2),
    created_at           timestamp(6) without time zone,
    current_period_end   timestamp(6) without time zone,
    plan                 varchar(255),
    psychologist_id      bigint NOT NULL UNIQUE,
    status               varchar(255) NOT NULL,
    trial_end_date       timestamp(6) without time zone,
    trial_start_date     timestamp(6) without time zone,
    updated_at           timestamp(6) without time zone,
    current_period_start timestamp(6) without time zone
);

-- ── Columns the Java backend added over time via ddl-auto=update ─────────────
-- A database snapshot taken at any point in the app's history still ends up
-- with the full set after this runs.
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS account_type text;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS permissions text;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS tenant_id bigint;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS phone varchar(255);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS credentials_changed_at timestamp(6) without time zone;
ALTER TABLE patient ADD COLUMN IF NOT EXISTS assigned_doctor_id bigint;
ALTER TABLE patient ADD COLUMN IF NOT EXISTS source varchar(255) NOT NULL DEFAULT 'Direct';
ALTER TABLE appointment ADD COLUMN IF NOT EXISTS assigned_doctor_id bigint;
ALTER TABLE appointment ADD COLUMN IF NOT EXISTS mode varchar(255);
ALTER TABLE doctor_availability_block ADD COLUMN IF NOT EXISTS mode varchar(255);
ALTER TABLE doctor_date_override ADD COLUMN IF NOT EXISTS mode varchar(255);
ALTER TABLE doctor_weekly_slot ADD COLUMN IF NOT EXISTS mode varchar(255);
ALTER TABLE doctor_service_price ADD COLUMN IF NOT EXISTS offline_offered boolean NOT NULL DEFAULT false;
ALTER TABLE doctor_service_price ADD COLUMN IF NOT EXISTS offline_price numeric(38, 2);
ALTER TABLE doctor_service_price ADD COLUMN IF NOT EXISTS online_offered boolean NOT NULL DEFAULT false;
ALTER TABLE doctor_service_price ADD COLUMN IF NOT EXISTS online_price numeric(38, 2);
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS payment_handled_by varchar(20) NOT NULL DEFAULT 'SELF';
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 0;
ALTER TABLE payment_submission ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 0;
ALTER TABLE subscription ADD COLUMN IF NOT EXISTS current_period_start timestamp(6) without time zone;

-- ── Drift fixes for databases created by older Hibernate versions ────────────
-- A whole-day date override has no slot time; older schemas made the column
-- NOT NULL and Hibernate never relaxes a constraint.
ALTER TABLE doctor_date_override ALTER COLUMN slot_time DROP NOT NULL;

-- Legacy single price/offered columns on doctor_service_price (superseded by
-- the per-mode columns). Still present on old databases, and NOT NULL there —
-- relax them so new rows (which never set them) can be inserted.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'doctor_service_price' AND column_name = 'price') THEN
        ALTER TABLE doctor_service_price ALTER COLUMN price DROP NOT NULL;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'doctor_service_price' AND column_name = 'offered') THEN
        ALTER TABLE doctor_service_price ALTER COLUMN offered DROP NOT NULL;
    END IF;
END $$;

-- ── Idempotent one-time backfills the Java StartupInitializer ran every boot ─
UPDATE appointment SET assigned_doctor_id = psychologist_id WHERE assigned_doctor_id IS NULL;
UPDATE appointment SET mode = 'OFFLINE' WHERE mode IS NULL;
UPDATE doctor_availability_block SET mode = 'OFFLINE' WHERE mode IS NULL;
UPDATE doctor_weekly_slot SET mode = 'OFFLINE' WHERE mode IS NULL;
UPDATE doctor_date_override SET mode = 'OFFLINE' WHERE mode IS NULL AND slot_time IS NOT NULL;

-- ── Helpful indexes (Hibernate never created any beyond the unique keys) ─────
CREATE INDEX IF NOT EXISTS idx_appointment_tenant ON appointment (psychologist_id);
CREATE INDEX IF NOT EXISTS idx_appointment_doctor_date ON appointment (assigned_doctor_id, appointment_date);
CREATE INDEX IF NOT EXISTS idx_appointment_patient ON appointment (patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_owner ON patient (primary_psychologist_id);
CREATE INDEX IF NOT EXISTS idx_invoice_tenant ON invoice (psychologist_id);
CREATE INDEX IF NOT EXISTS idx_invoice_payment_invoice ON invoice_payment (invoice_id);
CREATE INDEX IF NOT EXISTS idx_session_note_patient ON session_note (patient_id);
CREATE INDEX IF NOT EXISTS idx_app_user_tenant ON app_user (tenant_id);
