-- Psyfos workflow: case status (New Case / Ongoing / Periodic Follow-up /
-- Terminated / Dropped), follow-up scheduling, and service categories
-- (Counselling / Therapy / Assessment / Career / Other).
--
-- Purely additive: no existing column is renamed, dropped or re-typed, so the
-- old behaviour of every existing screen is untouched.

-- ── Case status, per client ──────────────────────────────────────────────────
ALTER TABLE patient ADD COLUMN IF NOT EXISTS case_status varchar(30) NOT NULL DEFAULT 'NEW_CASE';
ALTER TABLE patient ADD COLUMN IF NOT EXISTS case_status_updated_at timestamp(6) without time zone;
ALTER TABLE patient ADD COLUMN IF NOT EXISTS case_status_reason text;

-- Clients who have already completed at least one session are not "new" any
-- more. Runs exactly once (migrations are tracked), so it can never overwrite a
-- status a therapist set later.
UPDATE patient p
   SET case_status = 'ONGOING'
 WHERE EXISTS (SELECT 1 FROM appointment a
                WHERE a.patient_id = p.id AND a.status = 'COMPLETED');

-- Every status change, so the monthly report can say "3 cases dropped in
-- March" and the case history can show how a case progressed.
CREATE TABLE IF NOT EXISTS case_status_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psychologist_id bigint NOT NULL,
    patient_id      bigint NOT NULL REFERENCES patient (id) ON DELETE CASCADE,
    appointment_id  bigint,
    changed_by      bigint,
    from_status     varchar(30),
    to_status       varchar(30) NOT NULL,
    reason          text,
    created_at      timestamp(6) without time zone
);
CREATE INDEX IF NOT EXISTS idx_case_status_log_tenant_created ON case_status_log (psychologist_id, created_at);
CREATE INDEX IF NOT EXISTS idx_case_status_log_patient ON case_status_log (patient_id);

-- ── Follow-ups ───────────────────────────────────────────────────────────────
-- PENDING = a follow-up date is set but no session is booked for it yet.
-- BOOKED  = a follow-up session exists (appointment_id).
-- DONE    = that session was completed.
-- CANCELLED = withdrawn / superseded by a newer follow-up.
CREATE TABLE IF NOT EXISTS follow_up (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psychologist_id       bigint NOT NULL,
    patient_id            bigint NOT NULL REFERENCES patient (id) ON DELETE CASCADE,
    doctor_id             bigint,
    source_appointment_id bigint,
    due_date              date NOT NULL,
    due_time              time(6) without time zone,
    note                  text,
    status                varchar(20) NOT NULL DEFAULT 'PENDING',
    appointment_id        bigint,
    created_by            bigint,
    created_at            timestamp(6) without time zone,
    updated_at            timestamp(6) without time zone
);
CREATE INDEX IF NOT EXISTS idx_follow_up_tenant_status ON follow_up (psychologist_id, status, due_date);
CREATE INDEX IF NOT EXISTS idx_follow_up_patient ON follow_up (patient_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_doctor ON follow_up (doctor_id);

-- ── Service categories ───────────────────────────────────────────────────────
ALTER TABLE clinic_service ADD COLUMN IF NOT EXISTS category varchar(30) NOT NULL DEFAULT 'OTHER';

-- Best-effort categorisation of the services that already exist, by name.
-- Clinics can change any of these from the Services page afterwards.
UPDATE clinic_service SET category = CASE
        WHEN lower(name) ~ '(career|vocational)'                        THEN 'CAREER'
        WHEN lower(name) ~ '(assessment|testing|evaluation)'            THEN 'ASSESSMENT'
        WHEN lower(name) ~ '(counsel|consultation|crisis|guidance)'     THEN 'COUNSELLING'
        WHEN lower(name) ~ '(therapy|cbt|psychotherapy)'                THEN 'THERAPY'
        ELSE 'OTHER'
    END
 WHERE category = 'OTHER';
