// Bundles db/migrations/*.sql into server/migrations.generated.ts so the SQL
// ships inside the serverless function (Vercel only deploys files the bundler
// can trace). Runs automatically before `dev` and `build`; the generated file
// is committed so nothing breaks if a tool skips the hook.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(__dirname, "..");
const dir = join(root, "db", "migrations");

const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
const entries = files.map((file) => {
    const version = file.replace(/\.sql$/, "");
    const sql = readFileSync(join(dir, file), "utf8").replace(/\r\n/g, "\n");
    return `    { version: ${JSON.stringify(version)}, sql: ${JSON.stringify(sql)} },`;
});

const out =
    "// AUTO-GENERATED by scripts/embed-migrations.ts from db/migrations/*.sql — do not edit by hand.\n" +
    "export interface Migration { version: string; sql: string }\n\n" +
    "export const MIGRATIONS: Migration[] = [\n" +
    entries.join("\n") +
    "\n];\n";

writeFileSync(join(root, "server", "migrations.generated.ts"), out);
console.log(`Embedded ${files.length} migration(s): ${files.join(", ")}`);
